### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#15]
Die User Stories sind erstellt. Falls es Fragen oder Anmerkungen gibt lasst es mich wissen. Bitte gebt mir auch Bescheid ob ich irgendetwas vergessen habe.

**Comment by WasIsDaLos** [comment]
Ich werde am Montag dann jede User Story als eigenes Issue eintragen, also wäre es gut wenn Änderungen/Anmerkungen davor gemacht werden. @sweIhm-ws2018-19/fr-23

**Comment by LeaSindel** [comment]
Von meiner Seite würde ich lediglich bei Ermitteln des Grades des Verletzung bei Akzeptanzkriterien noch Ausschluss von Risikofaktoren mit aufnehmen.

**Comment by MiriRCNSE** [comment]
Mir wäre noch die Verwendung des Begriffs "Heilmittel" anstatt "Hausmittel" aufgefallen :)

**Comment by ChristinaBaur** [comment]
Klingt sehr gut! Dies ist ja quasi das Grundgerüst, vielleicht kann man am Ende noch erwähnen, dass wir den User freundlich und mit einem Schmunzeln (vielleicht Oma-Stimme und lustiger Satz) verabschieden wollen.

**Comment by WasIsDaLos** [comment]
Danke für eure Rückmeldungen. Ich werde die stories noch abändern und dann als issues eintragen.
