### ISSUE TITLE
Übungsblatt 1 Aufgabe 5

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#2]
Ich habe eine vorläufige Lösung für Übung 1 Aufgabe 5 ins Wiki gestellt.
[https://github.com/sweIhm-ws2018-19/skillproject-fr-23/wiki/Übung1-Aufgabe5](url)
Sollte der link nicht funktionieren bitte einfach selber ins wiki manövrieren ;)
Bitte noch einmal drüber schauen, ob es so passt.

**Comment by WasIsDaLos** [comment]
@sophiawagner39  Bitte nochmal drüber schauen und Verbesserungen/Fehler anmerken

**Comment by sophiajwagner** [comment]
@WasIsDaLos Sieht gut aus, ich habe keine Fehler gefunden.
