### ISSUE TITLE
User Story: Anwendung des Hausmittels

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#21]
![anwendungdeshausmittels](https://user-images.githubusercontent.com/43878791/48367624-95b3f980-e6b1-11e8-89f4-9a5b129c26fa.JPG)

**Comment by sophiajwagner** [comment]
Funktioniert gut, die genaue Formulierung der Tourismus-Studenten kann man ja dann später noch einfügen (Issue #29)
