### ISSUE TITLE
User Story: Alternativer Vorschlag

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#23]
![alternativervorschlag](https://user-images.githubusercontent.com/43878791/48367674-b7ad7c00-e6b1-11e8-868b-75a879815244.JPG)

**Comment by MiriRCNSE** [comment]
Alexa reagiert nur auf nein und nicht auf keine oder keines, obwohl die Synonyme korrekt eingetragen sind.
Ansonsten funktioniert es.
