### ISSUE TITLE
Verbindung von AlexaDeveloper zu AWS Lambda

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#24]
Im Moment sehe ich keine Option die .jar files in ein gemeinsames aws lambda hochzuladen. Ist ja schon n bisschen umständlich das dann jedes mal wenn ich testen will im developer uzustellen. Außerdem blöd wenn ihr das bei euch dann auch wieder ändern müsst. Oder habe ich da was übersehen?

**Comment by gsocher** [comment]
Stimmt, ein gemeinsames Lambda haben wir leider nicht. Ein (teilweise zufrieden stellende) Lösung ist automatisches Deployment von travis-ci in ein Lambda: https://docs.travis-ci.com/user/deployment/lambda/ und Informationen zu den Keys auf Moodle (Eintrag zu Lambda und DynamoDB)

**Comment by WasIsDaLos** [comment]
das funktioniert leider für uns nicht, da unsere aws keys immer nur eine gültigkeit von drei stunden haben.
