### ISSUE TITLE
Build Model

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#25]
Ich schaffe es leider nicht mehr ein neues modell zu builden im alexa developer. Die Fehlermeldung hilft auch absolut überhaupt nicht weiter. 
Fehlermeldung:
The attempted operation has returned an unspecified error. This may be due to an expired session, or a model that exceeds 2MB in size.
Kann mir wer weiterhelfen wie ich weiter vorgehen kann? Ich habe schon echt viel Zeit investiert und komme keinen Meter weiter.

**Comment by gsocher** [comment]
Ist das Problem noch aktuell oder hat es sich erledigt. In dem Account von Sophia Wagner (danke für den Invite) gibt es ein funktionierenden Build.

**Comment by MiriRCNSE** [comment]
Das Problem ist noch aktuell. Das Problem besteht seitdem wir neue Inhalte hinzugefügt haben. Wir kommen alle soweit ich weiß nicht weiter und wir wissen nicht woran es liegen kann.

**Comment by WasIsDaLos** [comment]
Das Problem wurde geklärt. Es ist durch einen kleinen Fehler im JSON entstanden. Es hat sich ein Punkt eingeschlichen wo keiner hingehört. Vielleicht ist das auch hilfreich für andere Gruppen. Hat uns sehr viel Zeit gekostet. @gsocher
