### ISSUE TITLE
Modellklassen erstellen

### ISSUE THREAD

**Issue by MiriRCNSE** [sweIhm-ws2018-19/skillproject-fr-23#27]
Modellklassen und JUnit-Tests werden erstellt.

**Comment by MiriRCNSE** [comment]
Modellklassen und JUnit-Tests wurden fürs erste erstellt. Nur kann man jetzt keinen Maven-Build machen.. Im richtigen Ordner liegen die Klassen soweit ich weiß. Kann jemand helfen?

**Comment by WasIsDaLos** [comment]
Also was ich bei anderen gesehen habe ist das maven ziemlich pingelig ist wo die junit tests liegen. mehr weis ich dazu leider auch nicht.

**Comment by WasIsDaLos** [comment]
funktioniert jetzt mit automatischen tests
