### ISSUE TITLE
Machbarkeit: Notaufnahme per webservice ermitteln

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#32]
Der Skill soll im Fall, dass er eine schlimme Verletzung hat die nächste Notaufnahme/Krankenhaus ermitteln. Teil des Issues ist auch zu ermitteln ob das möglich ist. Wenn es möglich ist muss ein neues Issue erstellt werden, in dem man sich darum kümmert den Standort zu ermitteln.

**Comment by WasIsDaLos** [comment]
Also hier ein kleines Update. Ich kann das nächst gelegene Krankenhaus ermitteln.
Das Problem ist nur Standortcoordinaten kann ich mit Alexa nicht ermitteln. Diese brauche ich aber für die Anfrage an den Webservice. Das heißt wir müssten nachfragen, wo sich der Benutzer gerade aufhält. Das können wir vermutlich auch einbauen. Die Frage ist wollt ihr das? Wird halt schwierig auf natürliche Art und Weiße nachzufragen wo man sich gerade befindet ;) Wenn ihr das wollt könnt ihr euch ja noch einen Text dafür überlegen.

**Comment by MiriRCNSE** [comment]
Alexa stellt die Funktionalität, die nächste Notaufnahme auszugeben, als Grundfunktionalität bereit. Vielleicht kann man diese auch mit unserem Skill verknüpfen..

**Comment by WasIsDaLos** [comment]
So wie ich das jetzt gesehen habe ist das leider nicht möglich. Aber das Ermitteln des nächsten Krankenhauses ist definitiv möglich.  Ich werde eine neue User Story dazu einstellen.

**Comment by WasIsDaLos** [comment]
Neue user story ist erstellt und wird in dem neuen Issue fortgesetzt
