### ISSUE TITLE
UserStory: VorangegangeneKrankheit

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#34]
![userstorydynamodb](https://user-images.githubusercontent.com/43878791/49292516-c23b8400-f4ad-11e8-9d3e-9e78dc72d455.JPG)

**Comment by MiriRCNSE** [comment]
Habe mir hierzu mal Gedanken gemacht, wie wir das lösen könnten. Allerdings bin ich in eine Sackgasse geraten. Eine Möglichkeit wäre, in eine Textdatei die letzte Verletzung hineinzuschreiben und zu Beginn (im LaunchHandler?) den Inhalt dieser Textdatei wieder in einen String zu schreiben. Wenn dieser String nicht null ist, könnte man vergleichen welche Krankheit vorliegt und dann hoffend fragen, ob alles wieder in Ordnung ist :) Jedoch sehe ich das Problem, dass dies nur einmal funktioniert.. Da wir die gleichen Dateien für verschiedene Benutzer verwenden. Der Skill würde zum Beispiel die Sophia fragen ob der Bienstich wieder verheilt ist (den eigentlich ich hatte). Auch ist die Frage, da die Textdatei sich jedesmal verändert, müssten wir den Code jedesmal extra auf AWS hochladen? Vielleicht habe ich etwas übersehen oder ihr habt eine andere Idee wie wir das lösen können?

**Comment by sophiajwagner** [comment]
Hey :) 
Die Verletzung würde ich einfach in Dynamo DB speichern. Dazu würde ich einfach vorgehen wie in dem Testskill Lieblingsfarbe, was auch unter [https://moodle.hm.edu/mod/page/view.php?id=351747](https://moodle.hm.edu/mod/page/view.php?id=351747)  beschrieben ist und der Code dazu ist ja auch nochmal im Skillproject test. 
Und das Problem, dass eventuell bei verschiedenen Benutzern derselbe Wert gespeicht wird, würde ich einfach ignorieren. ;)

**Comment by MiriRCNSE** [comment]
Super danke Sophia! :)
Dann mach ich das bis nächsten Freitag ;)

**Comment by LeaSindel** [comment]
Dialog dafür:

Hallo! Geht es deinem X wieder besser? 
         -> ja -> Super, wie kann ich dir sonst helfen?
         -> nein -> Ohje, dann solltest du vielleicht zu einem Arzt gehen. Möchtest du wissen, wo die nächste Notaufnahme ist?
                                           -> ja (und dann von Alexa die Notaufnahmen
                                           -> alles klar, wie kann ich dir sonst helfen?

**Comment by MiriRCNSE** [comment]
Habe das Grundgerüst noch ohne Dynamo DB erstellt, so ist es jetzt auch im normalen branch für den sprint2 drin. 
Dann habe ich Dynamo eingebunden und seitdem schmeißt es mir die Meldung, dass es die Conversation Klasse nicht mehr initialisieren kann.. Habe die Dateien in einem Extra-Branch sprint2_problem hochgeladen. Sitze nun schon seit Stunden dran und finde den Fehler nicht, vielleicht könntet ihr mal drüber schauen? wäre echt super :)

**Comment by MiriRCNSE** [comment]
also der Fehler wird in dem MyInjuryIsHandler in Zeile 54 geschmissen. Dort habe ich allerdings nichts verändert...

**Comment by WasIsDaLos** [comment]
Wir haben entschieden das diese User Story doch nicht umgesetzt wird, da sie dem Grundgedanken des Skills wiederspricht. Man möchte in einem akuten Notfall möglichst schnell Hilfe erhalten und nicht erst nach der letzten gefragt werden. Aber trotzdem danke für die Arbeit und Mühe!
