### ISSUE TITLE
Handler testen

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#35]
Die Handler müssen noch getestet werden.

**Comment by fabiseid** [comment]
Alle HandlerTest sind hochgeladen.
Probleme gibt es mit dem Wrappen von Values in den HandlerInput (bei NearestHospitalIntentHandler und MyInjuryIsIntentHandler).
Testfunktionen sind beide auskommentiert

**Comment by WasIsDaLos** [comment]
Funktioniert sehr gut. Ich habe in dem YesIntentHandler noch einen Test auskommentiert, weil er leider fehlgeschlagen ist und travis ci dann nicht builden kann.
