### ISSUE TITLE
Kommunikationsverlauf wie in getstoryline erstellen

### ISSUE THREAD

**Issue by sophiajwagner** [sweIhm-ws2018-19/skillproject-fr-23#40]

**Comment by MiriRCNSE** [comment]
Habe noch kleine Fehler in der Kommunikation korrigiert. Zum Beispiel, dass der YesIntent Handler bei der Frage: "Haben Sie eine Zitrone oder Zwiebel zuhause?" nicht nur auf ja reagiert, sondern auch auf Zitrone und Zwiebel reagiert.

**Comment by WasIsDaLos** [comment]
der Gesprächsverlauf ist angepasst und entspricht jetzt dem aus get storyline. Abweichungen am Anfang werden im nächsten Sprint noch nachgezogen. Schöne Lösung.
