### ISSUE TITLE
Sounds hinzufügen

### ISSUE THREAD

**Issue by MiriRCNSE** [sweIhm-ws2018-19/skillproject-fr-23#43]

**Comment by sophiajwagner** [comment]
Hab grad nachgeschaut, unter [https://developer.amazon.com/de/docs/custom-skills/ask-soundlibrary.html](https://developer.amazon.com/de/docs/custom-skills/ask-soundlibrary.html) gibt's so Sounds, die man ganz einfach einbauen kann (hab's schon ausprobiert, funktioniert auch ganz gut)

**Comment by sophiajwagner** [comment]
Es gibt jetzt nur den Sound für das Umblättern, weil die Tourismus-Studentinnen keinen weiteren wollten.

**Comment by MiriRCNSE** [comment]
Sound wird korrekt abgespielt, wenn Alexa in ihrem Büchlein blättert :) Weitere Sounds waren nicht erwünscht, daher passt alles :)
