### ISSUE TITLE
Fehler in SonarCloud beheben

### ISSUE THREAD

**Issue by sophiajwagner** [sweIhm-ws2018-19/skillproject-fr-23#44]

**Comment by WasIsDaLos** [comment]
Die Anzahl der Bugs, Vulnerabilities und Code smells soll auf 0 reduziert werden, so wei dies möglich und sinnvoll ist.

**Comment by WasIsDaLos** [comment]
Stand Freitag 16.12.18 waren alle Fehler behoben, bis auf ein security Problem mit regex-Ausdrücken. Das Problem wurde wahrgenommen, aber für unser Projekt als nicht relevant eingestuft.
