### ISSUE TITLE
UserStory: Ermitteln der nächsten Notaufnahme

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#45]
![userstorynotaufnahme](https://user-images.githubusercontent.com/43878791/49646978-354e7880-fa21-11e8-8cfe-fb583d68cd91.JPG)

**Comment by WasIsDaLos** [comment]
Die Modellklasse, die die nächste Notaufnahme ermittelt ist so weit fertiggestellt. Sie muss nur noch in den Dialog eingebunden werden. Das heißt ich muss irgendwie von dem User erfragen, wo er sich gerade befindet. Das ist rein theoretisch über ein freitext intent möglich. Aber ich brauche dann einen eigenen Intent, der mit irgendetwas wie "meine Adresse ist [freitext]" startet, da ich sonst nicht an die Informationen komme. Das ist leider kein natürlicher Dialog mehr.

**Comment by WasIsDaLos** [comment]
Das Ermitteln der nächsten Notaufnahme funktioniert und ein entsprechender Intent wurde ebenfalls erstellt. Es müssen nur noch Tests geschrieben werden

**Comment by MiriRCNSE** [comment]
Es wird ein Krankenhaus in der Nähe ausgegeben, wenn man seine Adresse angibt. Etwas umständlich, dass man nicht seine Adresse ohne vorangehendes "meine Adresse ist: ... " oder "Adresse ... " eingeben kann. Jedoch ist dies glaube ich nicht möglich, da sonst ein anderer Intent ausgelöst wird :)
Super, dass du es geschafft hast, dieses Feature einzufügen!
