### ISSUE TITLE
Ü2A8

### ISSUE THREAD

**Issue by WasIsDaLos** [sweIhm-ws2018-19/skillproject-fr-23#6]
Ich habe eine vorläufige Lösung für Aufgabe 8 von Übung 2 in das Wiki gestellt.
Bitte nochmal drüber schauen.

**Comment by sophiajwagner** [comment]
Ich habe deine Lösung geprüft und ein paar Änderungen vorgenommen: 

- ich habe sowohl Objektname als auch Klassenname hinzugefügt (wie auch in der Musterlösung von Blatt1) 

- ich habe den Objekten einzigartige Objektnamen gegeben 

- die Namensgebung "Dokument1" und "Dokument2" in der Aufgabenstellung habe ich so verstanden, dass das die Werte für das Attribut "name" der Klasse Dokument sind.  


![aufgabe8](https://user-images.githubusercontent.com/43878358/47655007-5c956880-db8c-11e8-82ea-0fd85ca33816.png)


Falls du auch noch was ändern willst: 
[Edit](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#R7VlLc9owEP41HJOxZSBwDI8kh3amM%2BlMk94UW9gqsuXKMoH8%2BkqW%2FJAf4CZAk0w5JNKn1dq7%2B%2B2uEANnHm5vGYyDr9RDZAAsbztwFgMAbGsIxD%2BJ7BQyAo4CfIY9LVQC9%2FgF5Ts1mmIPJYYgp5RwHJugS6MIudzAIGP02RRbUWI%2BNYY%2BagD3LiRN9Af2eKDQCbgq8TuE%2FSB%2Fsj2eqpUn6K59RtNIP28AnFX2UcshzHVpQ5MAevS5AjnLgTNnlHI1CrdzRKRvc7epfTcdq8V7MxTxPht0WBK%2By01HnvCEnlLGA%2BrTCJJlic4y85BUYIlZwEMihrYYoi3mDxqW40c5vhzJWcTZ7sGcPmrJX4jznaYATDkVUPncL5TGufbIu5ahFdOIRkghN5gQrSfhjK7RnBLKMkscK%2FtkK5Dx2t4Mq%2BxWfpDGG55MaMpcDRVMhMxH2rsAND1uF3EU%2BYFoiISxQoQhAjnemPqhJqpfyBVbv1EsNAIrT6qhpoxOKTAyNag31ZuqEa%2FpGY8MNYXaXI%2ByrqFHDCrWlFDGp3ZujU%2FCLUUgzS77bNx6NYOqbJmciyz1IE%2BtXmR5RZC1SRtIUpSXvDERxs1SMfDlgKMtlzID51r8%2FS5muYhQXkg1yFIJvn4GYkJVZ6Hr8GSeLlfaBc9lPbcdjQWVWj6yup1t%2BGmPU6b9nGL%2FM6cUNcXkybTFR%2BBEPspb%2FSnLg1UtD7ZRHDK5Pml9qDT0LTHd7alH67HbWk%2F%2FcL%2BxmoDJ%2FtZzvJaR29mSOR7elFlRSyafwRVel%2Bn0M01gGKLIRwniLxzdZuv5tqe6nidWR8R7NqTMvCww471Omq2OdThbpy3ZOj5GtoIzZ2utmdsfKludZrbaJ8jW3sFzDvcjlUJlm17iaAXdoJY6Z%2BxNwJm2n2GMBg5O1JyG%2F%2Bnen%2B6jd0b3UV%2B6O%2B%2BH7kPH7LHtdD%2FRWQx0t93YMHr8O5U3E7NQhBpHynVWvM3cOMvuNyR%2BwSWx5NqwsiZPvBeQYF%2Fvc4VnEDOXPeRSJthAtYxMKEawYHbx6DweHl2nosVXDtELjby9z8d1LGjsfJVfCFpxtTiRi3WTIhiibMuiYo299%2B3jTnpKNmIXkmvl8UUWk5n2%2F0K9yYwKqRXJ6scqqxqzFY24Lhii56v5DQwxkby8Q2SDpFazvh2B%2FsU1xCG6H%2BMwk1%2FafES6g09Od%2FC56b6rUfssdD%2FqJe%2F7OJbsOzh1HFka0Wn7On38787W9LL9a9vfXtw2NfW8uhWhgLuKWCwFkj2vbJtHkbFVY5tS2PM7vpiWP2co8fI3I2f5Bw%3D%3D)

**Comment by WasIsDaLos** [comment]
Die Bennenung der einzelnen Objekte ist nicht unbedingt notwenig, aber mit den Dokumentennamen hast du sicher recht. Danke

**Comment by WasIsDaLos** [comment]
Ich ändere die Daten im Wiki noch
