### ISSUE TITLE
Übungsblatt 2 Aufgabe 2

### ISSUE THREAD

**Issue by sophiajwagner** [sweIhm-ws2018-19/skillproject-fr-23#7]
Hier ist meine Lösung zu Aufgabe 2 aus Blatt 2: 

![aufgabe2](https://user-images.githubusercontent.com/43878358/47616495-c561df80-dabd-11e8-9301-32e595ef3d3b.png)

Für Änderungen: 
[Edit](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#R7VxJc%2BI4GP01HObQXd5k42MgycyhuyZV6apZbgIEqDEWZYsk9K8fyZaMtaQxIDPd0LnEkrVY733St0hiEI7Xb78XcLP8TGYoGwTe7G0Q3g%2BCwPeAx%2F7xnF2dA4KwzlgUeCYK7TOe8Tcka4rcLZ6hUilICcko3qiZU5LnaEqVPFgU5FUtNieZ2usGLpCR8TyFmZn7F57RZZ07DJJ9%2Fh8IL5ayZz9O6zcTOF0tCrLNRX%2BDIJxXf%2FXrNZRtiYGWSzgjr62s8GEQjgtCaP20fhujjGMrYavrPb7ztvnuAuW0S4WgrvACsy2SXxxnrOpowh4W%2FOFuRTHJZTZrqnkjhkB3EjY2mg1%2FRG%2F8dQUD4h35LLWk60w8vi4xRc8bOOVlX5kENW29oIKit3fH4jcIMclDZI1osWNFZIVIgCqELhHJ1z2DvsR92WJvKPKgEJpF0%2FIeOPYgsLPjGFpwfAecYknWk22pQsIHjpn8fYITlD2REleYh%2FcTQilZtwrcZXiRr2tEKHGEXJSqyPmeCV1kQS5ygFx0GDk0Y5NTJFE2Ia8P%2B4w2iNU79rwkBf5GcgrZixHkgHHY689WgWwjjPLZHV86WF5OcqQIsMdSGadm1MzvMclIsS9bUlhQWZ9sUC7zxOLmBw1VfDgKUSXZFlOkCFIH7gqUQYpf1KZsTIiqTwSzFhvOga9yHmtcsm9fICoqaXQ2X9GJYWAyDEZvbBGBay6%2F9VLCMQb3Z1Mv2e1ItCDqGKJZ7R%2BV0lijtFnt3HMaf5%2FTSlX8IvRcQqPLEZoYhE5%2BY%2BmHnJZTtuTPtvli0BgtezpprepbxBWoxN%2FgpCrAwd%2Fwj6s%2BF4y4QLAVeUuZgqsRby3QGZrb1udayZXMWsD54gtP3H%2BI3Ki9ME0VeKPANBg8i9rTWThF7Q0NvCHHWxpbV4a0Zl9EoQF03BPOqYHzlOP877aEa2ZGzQfjcDAaL4tKvsXqlU%2FK2rC6bhYab6st72FPPMi%2BnFvINV4287jRDw6gCzwNO3A5C9n3D0N3GRP5SLWqKeXjFa0Umv41bSPjgt8w7E3T%2Bjaf%2BwJWks1DceDz%2FLCUhhqlTTygB0o7uP%2B%2FKD2fUv%2BClJqGw4wbDl8Qzipb4ZoMA90QblbDlnZLejIMAtMwQBzo510%2BXRYkxyW8BZM4TC3Oh98X5qZFMa8w57N%2FlRPKVpKrAtvw9CwBzrQvsE19v6hd69k1Qq3JNbAYysO%2BkDbV8JIj%2FefkK1rdhFzb0O4thGEN3de7RDP8IjeJcCXrbOQwXzAMCsj6QUVrO6lV9rrI0WZC4scmN32525ag%2B9cqvrQtdSKuCXJ9PiTeJTE3g%2BIrjvkTU6p1tOKqsNbEO7Wo1N5sRjNanVmi1XwX%2Fr1Q3zUxoUt9agnsNbi75iI07XcDXVYDb0rN0ZXRvtrlpJDy93OcZdIlHbC2q7%2FKLy3ICrXezOfijQP8okizDiMTP9uioceIToKvSzToe%2FDxqNr%2FCZ5%2B6gIMweXAs2xDGuDZ4pCPOGviLWpUsoXwwB766ABNW9vIjY1zQx9J9BGoUqoHP%2BqYjBH86NBUcxbgQByFAQl3rWJiTTzmo1PlPBJ7qNs8NUwTmprgaiUgSnUw9TnUWQLMpjpG0o6WALMn4FgCzJ3Uq5UAPYpxMv96Q32xr%2FfjmPuoQ9w9wyKwzXWgPMwZqSxvUIFrbyi85yc4JyRHT%2Fs8i%2B1HtpQ3PG7On7rSpqE2W2JTm9rCJ%2FoCftJJPDPkbaC535q1HeI0Js5ZWAAQaGuH73mBAYdETDEu4vPhAF22Xa9jYQGJ5suBExcWEOvL%2FZ6yHg4WWk4WumOI8VDs%2FhZTu0r8wxNsfN3ZC7x6tO0JdhFGzRO9uq%2FXmVJwqCVHygIE73TkSluAXr2FRlz8j16gSkwKZLqlVFoa41g5ApeTIzBMjAl9qiTFkXewLUeyFHvvfrYzabodz0NXD74nje6jFxOjpbSbAJxCkMUx6HZG%2BacOBpoQdzyq5iIYCCwmZOez%2Fj837GmkwW4xVUFPsMedduJUyVdTM0hhSUmBNKr0lHXTztaTeodM3YEVLwu9uHq3rNMGYXNktPLCDl0yk%2BIxZaRWjp0D4vXgMUjN6eZHvkm8fuHmJOJtJs1hOuR27IdjkD%2FcrLG764Rit06l76t2QWK7JWg7d6O7RCfRdTuxqmYHWuKcNqHgY40G5o4easrhxSZbEOSw6Mt99RucUcDXff6LzinZ1w3MKV3VJNLmONoM9w805PBeWXCYnp8rRBvFqqUXWg4%2B9BWiTbocNL8SYU%2BG2rISeicqEEtTUTcFcmzcwdKT0IOuwg5Jl%2Fvy1yEBIHAmAZamepIAS0%2BuJeB2Dj0AL9TADOJTJcBoyhAmVxJgfvTQrQQMzZ2p1hlD784Qh%2FIVrzNYKdk5yam8hsQV4nSJs9knuGPaclCdxZquZGrUviRYnzlq3Q7i41dOHIkbRPtKz7wx0U0VyUFPUop8LeszfFMKfoKl1NhTkmVwU%2BI6CsQrrhlPOB%2BJS1BVITnAR%2FUElPjpHYvjX8EgZoCjCJCvXdZPo8SwC2x3DHy5i33WdXJzUWiLhCVw8ksk%2BhcJ%2FdZwnyLBkvufjaoXlf1vc4UP%2FwE%3D)

**Comment by sophiajwagner** [comment]
@WasIsDaLos Bitte nochmal drüber schauen.

**Comment by WasIsDaLos** [comment]
Schaut gut aus. Ich glaube aber das man bei Ein- und Ausgangsparameter (i,j) noch die Aktivität mit einzeichnen muss. Also das Kästchen mit den runden Ecken.

**Comment by WasIsDaLos** [comment]
Ich habe hier mal den neuen Vorschlag erstellt: vielleicht kann man den roten Rand bei End und Anfangsknoten noch entfernen.
[Neuer Vorschlag](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R7VzLkto4FP0aFrOYlN%2FGy4buzCySmq7qVM1jJ7AApY1F2SJAvn4kWzLWg8aATCeQXnTZki3J51zpPnTFwB8vt38UYLX4jFOYDTwn3Q78x4HnDWOP%2FmcFu7ogiKK6YF6gtC5y9wUv6DvkhQ4vXaMUltKDBOOMoJVcOMV5DqdEKgNFgTfyYzOcyb2uwBxqBS9TkOmlf6OULPhnefG%2B%2FE%2BI5gvRsxsldc0ETF%2FnBV7nvL%2BB58%2Bqv7p6CURb%2FEPLBUjxplXkPw38cYExqa%2BW2zHMGLQCtvq9jwdqm3EXMCddXhjycX8D2RqKIVcDIzsBRvU5kL3gDvzRZoEIfFmBKavdUPZp2YIsM17Nm4MFgduDY3KbL6UCBPESkmJHH%2BEvBF5Yv8KFJw7iD7xksyfDjXjZokVEwssA53%2FeNL7HgF5wGA5AEv94kLjxu0LiGRCJMtrBaEIv5uzi4ZUgnIti2mBTo4FHZX7FLuGWVctQtmAzoXoANwO6h6EMHBlKR8dRzM42jkPnchz945IlwCkWeDlZlzIk7CsRXaU%2BgQnMnnGJKsz9xwkmBC9bDzxkaJ4va5AItoRckMjIuY4OXWBALrCAXHAcOZjSJZzfwmyCN0%2F7gjaIVR29XuACfcc5AbRiBBhgDPZ62DKQbYRhnj4wBUPLcpxDSYAdepcxakaNFhjjDBf7Z0sCCiLexyuYizKuAl3vLapKvC6mUBIl9tFvclfADBD0TdZrJib4q88Y0V4bzkNX5jxSuKRjn0PCX1LobEbRieFQZzgcbekiApZMfuulhGEcPl5MvWC3I9GcqFOIpm%2F%2FqJRGCqXNamef0%2BhtTitV8YvQSwkNrkeobhpNfqP3Tzkpp3TJT9f5fNCYtns6Sa3qW8QVsETfwaR6gIG%2FYoOrhhuOmEDQFXlNqIKrEW8t0BmcmdbnWsmV1FpA%2BfwLu3n8PbCj9vwkkeANPN1gcAxqT2XhLFtUwxswvIWxdWNIK%2FZF4GtARz3hrHtBU4bzf%2BsSLKkZNRuM%2FcFovCgq%2BearVz4pa8PqtllofPK2vPs98SD6sm4h13iZzONGP1iAznMU7MLrWciuexy665jIJ6pVRSmfo2iF2PStaRsZ5%2Fz6fm%2Ba1jX53FewkkweigWf54el1FcobeIBPVDawf3%2FRenllLpXpFQ3HFJmOHyBKKtshVsyDFRDuFkNW9ot7skw8HTDADKgX3b5dFHgHJXgHkxiPzE4H25fmOsWxazCnM3%2B1xwTupLcFNiap2cIcCZ9ga3r%2B3ntWqe3CLUi16HBUB72hbSuhhcM6b8mX%2BHrXci1Ce3eQhjG0H29S5Sib2KTCFWyTr8c5HOKQQFoP7BobSe1nr0tcpSZELuRzk1f7rYh6P61ii%2BtS5WIW4JcnQ%2Bxc03M9aD4K8P8mSrVOlpxU1gr4p0YVGpvNqMerc4M0WqWq3Eo1HdLTKhSnxgCew3utrnwdftdQ5e%2BgVal4uiKaF%2FtchJAWP0MZZlwSQe07eqv8ksL%2FApbNbMZr7GAXxAo1mGg42daNNQY0VnwdYkGvQUfi6q9J3hq1kU41NNXegPPsA2pgWeKQ35EWRNvkaOSWnaPAZyjYQ4pc4d%2F56Whjzj4IGcKBWrwo47IaMGPDk01uQBH4igUSLBrPcbXxFMGnUhZa%2FSibvPcMI3fIaXrViQgSFQw1TnUWQL0pjpG0k6WAL2n0LIE6DupNysBahTjbP7VhvpiX%2B3HMvdBh7h7hnhgm%2BlAkfIbyCyvYIFqb8h%2FZHm%2BE5zD532ZwfbDa8IaHjdZyra0qa%2FMlkjXpqbwibqAn5WJ1yVjuNma7ZQaexEWYegpa4frOJ4Gh29IjRWGwSVwhF22XW9jYQljxZcLz1xYwkhd7veU9ZBYaMgstMcQJabY%2FcOndnXzL7uh3%2FcGe%2FXHyfPpPRjVM3pVX68zpeGxliwpi9A70JEtbRH26i004uJ%2BcDxZYpJQ3LeUytsaoy1H4TvKUTiMtQl9riRFgXO0LUuyFDkHh21Nmu7H81DVg%2BsIo%2FvkxURrKekmAOcQZHAMuuUo%2F9TBQB3ijqlqNoKBocGE7Jzr%2F3PDngQK7AZTNewJ9qjTTpws%2BfJdCggoCS6gQpV6Z9y0M%2FUknyGTd2B5ZaE%2BLp8t67RB2KSMVl7YsUNmQjymlOfKsbNAvBo8DhN9urmBqxOvHrg5i3iTSXOcDrEd%2B%2FspyB9vVtvdtUKxXafSdZXzlqZTgqa8G9UlOouu%2B4lVeepR36QJBZ9qNDQHXQ83ZfFgkykIclz0xb76Hc6o0FV9%2FqvOKdHXHcwpVdXEwuY42Qx3jzRk8VyZd5yenytEG0SypecbEh%2F6CtHGXRLNb0TY46GyrPjOmQrE0FTQTYGcGncw9MT1oK2wQ9zlvPxtSEDoWZMAQ1M9SYChJ9sScD9JD6HjK2B60bkSoDWlCZMtCdAHPbQrAUN9Z6qVY%2Bg8aOJQbtAyA5WSneGciGNITCFOFyhLP4Ed1ZaDKhdr%2BiruRu1DgnXOUet0EPt%2BKeOInyDav%2FTCGuPdVJEc%2BCzEylWKPoOt9OAnUAqNPcVZBlYlqqNA7MUl5QnlI34IqnpIfOBHOQOK%2F0CTwfGvYOAzwFIEyFUO6ydBrNkFpjMGrtjFvug4ub4otEXCEDj5JRL9i4R6arhPkaC3%2Bx8XqxeV%2FQ%2B4%2BU%2F%2FAw%3D%3D)

**Comment by sophiajwagner** [comment]
Ja stimmt, mit den Ein- und Ausgangsparametern hast du Recht. Danke. 
Der rote Rand war von draw.io so voreingestellt, aber hab ihn jetzt schwarz gemacht.
