### ISSUE TITLE
Übungsblatt 2 Aufgabe 3

### ISSUE THREAD

**Issue by sophiajwagner** [sweIhm-ws2018-19/skillproject-fr-23#8]
Hier ist meine Lösung zu Aufgabe 3: 

![aufgabe3](https://user-images.githubusercontent.com/43878358/47775507-2670f980-dcf0-11e8-9a2c-dd864a1067c3.png)

Zur Bearbeitung: 
[Edit](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R5VlNc%2BMoEP01Ps6WJSTZOSaeZPawU5WqHGZmb1jCEhUkvAjHzvz6aSTQB8gTRyPHrlofEtFAA6%2Bfmu7WDK3ywxeBt9lXnhA28%2BfJYYY%2Bz3zfmwc%2B%2FFOS11oS%2BqgWpIImelAreKI%2FiZmppTuakLI3UHLOJN32hTEvChLLngwLwff9YRvO%2BqtucUocwVOMmSv9RhOZ1dKlv2jlfxOaZmZlL7qpe9Y4fk4F3xV6vZmPNtWv7s6x0aUPWmY44fuOCN3P0EpwLuun%2FLAiTGFrYKvnPRzpbfYtSCFPmaDN8oLZjpgdV%2FuSrwaL6jREjZ%2FP0N0%2Bo5I8bXGsevdgfZBlMmfQ8uDRXV9v6YUISQ4dkd7PF8JzIsUrDDG9kcZGc8cLdHvfWiK40bKsY4XQTMTa%2Bmmju0UAHjQIw4AsHEAecCaIcGABy23V4y5nt7HkAg6vzkiBRP%2FgNWGPvKSS8gKGrLmUPIcBTHXcNRRZcabmfW5J0uq4ZTRVcyW3EOY7yWhBVg3z59PAbqGOotBBHQ2APgXmSwfzr1Ru%2Fh%2BwL%2FzL4e55DvCK7BJEhBYpWZPCwR80gBMmH%2BIJ%2FKCPTTCAjecPgLOcAhz%2FGCtTwkhKClhQIVXu4uzCOKEg7HvMpesxz4eTe4VcK05BeEk%2BBQ5OTxIL%2BQlkKlzw5%2F%2Fuaakw%2BkmraIqIDS7LS1MLWe5pMUCt8Fz%2BKXQgu5d4uyXF5prclHfTxyhcDtBqPoRROAFGkYMRgLLBQCSQXpU7Rx76K7wgUm5o58JRJLcqfYBWwQvShwBOLl6%2F66u%2FavxQDTgTNA9Ufjfj4LnuQdZPdz4SQWH7RLwVRpR8J2LSC0zBZaTEjNIHIEkvm3EN0IF36F01MkEYlvSlnwMNQa5XeOS0kJ33YH4klDEq6uPoWd2kxFZk%2BWnkWYpqEBxFFQOaY59GipupSOEdJ8X8bKRYXj0pIr%2F%2FyqPQuhhOJUW0sBTNLUXTkeKUrHgUKYZMr3pt2w8TJzyVFSau79JicVWsaAo9JhJDI1nhpK12qDYhK9wAbpr7472s8EayArmsWF4VK8KFHZ%2BP9RVWUh14Z2MFcnPo37FizXj8XBnYVD0hgKuaD1StURm6yxnjCZoL5UeXQA6bfhuq9dgQDlwd3vvp0FTr%2FtQjWCZruPBuj2BH47aiCW3vlgg%2B2PbeONtH12V7ZNt%2B7HsfeB9n%2BxOyiY4t7fpiU5vs8INDYguSBJdZVW73elxZnpURA3eDKVi8yYg%2F9fp2LDA2QgzQG4omtP4JacMlrD%2FyLhiIFz%2FK%2BshKGoNgrN%2B373xb0XTWN5p71o8YIHe34dWeWhpE%2F%2B246fhUVsa8hQEe2h7aTnhK1f97kVMp2a5IlXZewF%2B3lqqqOPVisM96vXq2w0BJDrJ%2FpZRS8GdiPoDoEHUDt48lwpqoMdCGiAEG5zRJ2LGyUf%2BLocbKLhMNsHL6T4J2WnFC3Qia7efXmhztN250%2Fws%3D)

**Comment by sophiajwagner** [comment]
@WasIsDaLos Bitte nochmal drüber schauen. Bei den gestrichelten Pfeilen bin ich mir nicht sicher, ob noch was dazugeschrieben werden muss.

**Comment by WasIsDaLos** [comment]
Ich glaube hier fehlt noch dass man Mitfahrgelegenheiten von beiden Seiten aus auch absagen kann. Ich denke es sollte so aussehen:
[link](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1#R5VpLc%2BMoEP41Pk5KEno4x8TjzB5mqlKVqZqZvWEJS2yw8CIUO%2FPrFyz0AjSxFTl21eaQSA008PVHd9PKDCw2%2By8MbrNvNEFk5jnJfgY%2BzzxvHnnitxS8VgI%2FDCtBynBSidxW8IR%2FIyV0lLTECSp6HTmlhONtXxjTPEcx78kgY3TX77ampD%2FrFqbIEDzFkJjSHzjhmdqWF7XyvxBOs3pmN7ytWlYwfk4ZLXM138wD68NP1byBtS610SKDCd11RGA5AwtGKa%2BeNvsFIhLaGrZq3MNAa7NuhnJ%2BzABQDXiBpET1ig%2Fr4q81FofdINnfmYH7XYY5etrCWLbuhPGFLOMbIt5c8WjOr5b0ghhH%2B45IrecLohvE2avoUreGChvFHddX77vWEv6tkmUdKwT1QKisnza6WwTEgwLBDkhkAPIAM4aYAYuw3FY%2BlhtyF3PKxOblHrEg0Ve4QuSRFphjmosuK8o53YgORDbcNxRZUCLHfW5J0uq4IziVYznVEKYlJzhHi4b5zjSwa6iDMDBQBxbQp8B8bmD%2BDfP1%2FwP2yLsc7q5rAC%2FJzoUI4TxFK5Qb%2BAsNwgmjD%2FEEnt%2FHxrdg43oWcOZTgOMNsTJFBKUoFxNKpIoyzi6ME%2FCDvsecmx7zbDj5ZsRAiQim6pUyntGU5pAsW%2Bl9P6Z00EB7zH9K8U2g3n7VLblYWKdJvv5SCv5BnL%2BqLAKWnMrz2sz7lcqzfNCRwCI7zFopTO5kqiAXuRUWPEgesNxo53DLvQzGViUqaMniupeKqBwKnqhu%2FoD5GCKQ45e%2B%2Fndx1gzn18pZP7jk2fYNnJ6EwfgnIZOpm%2Bf8vcOFxOg3PiS2iK1hUVz6mAMtVESWYx6cK1YEBmRLDrfi4KyvKWS4t32MgrmFVo4No2ACjEIDIwHKGgoiCelVhVbggpvggkiZabYJR%2Bufc5ojLU400aAXC5qo8bMTT6oWoP2oxkfEsFg%2BYm%2BldF0nH5k%2Bvk4XtHhhGqADr%2B2s1rKjY4Oa4ZHinHfOgTOQVtYqqu2oUd0Loq5I89PA1RRVIBiKDgxotn0cKW6nIoU7TArnbKSYXz0pQq9%2F5EGgBYZjSRFGmiJHUzQdKY6pUIwihc30slW3vZ04wbGsqO9YXVpEV8WKpuhWZ2JgJCuMEoKeqk3ICjOBmyZ%2BnMoKdyQrLLeE%2BVWxIoj0%2FHysr9AKHL57NlYAs57xJ1asCI2fq2ufujuKBE6%2FBb55N3UG2fTHVK3HhsASOtzT6dBUTt%2FrETSTNVw42SPo2biuaELbe5e2vTvO9uF12R7oth977n3342x%2FxG2iY0u91tvUic2KkF4wUlyZn5URlthQFyzeZMR7vb6eC4zNEH3whqIJrX%2FEteES1h8ZCyz54kdZH2iXRt8f6%2Ff1mK8rms76teae9UMikLtf08OaWhqE%2F5a0bvhUHIx5Jzq4YLtvG8VTKv8u2QZzTso8ldppLn6btVRZxakmE%2Bus5qtGGwzkaM%2F7IaXgjD6j%2BmOUSlHXIvpoIqiIGgvaIGZh8AYnCRkqG%2FUr7YMU%2FIDPs%2Fq1YtTHBluGVxkgwS81%2BLaad2OlTj%2FLULgqYNpadcX0vroGPcU4rYZnwG4xznAJHegVvOjGUsM7V0XYP%2B0OJn3q9wwbftWSZJmXqkm%2BzFg869CXmY%2B5Y%2Fmavw30C%2FPR0VYr0gX6WRvtb8Vr%2B88oVff2H37A8j8%3D)

**Comment by sophiajwagner** [comment]
Ja stimmt.
